var hierarchy =
[
    [ "Oddity.API.Api", "class_oddity_1_1_a_p_i_1_1_api.html", null ],
    [ "Oddity.ApiConfiguration", "class_oddity_1_1_api_configuration.html", null ],
    [ "Oddity.API.Models.Api.ApiInfo", "class_oddity_1_1_a_p_i_1_1_models_1_1_api_1_1_api_info.html", null ],
    [ "Oddity.API.Builders.BuilderBase< TReturn >", "class_oddity_1_1_a_p_i_1_1_builders_1_1_builder_base_3_01_t_return_01_4.html", [
      [ "Oddity.API.Builders.Api.ApiBuilder", "class_oddity_1_1_a_p_i_1_1_builders_1_1_api_1_1_api_builder.html", null ],
      [ "Oddity.API.Builders.Capsules.AllCapsulesBuilder", "class_oddity_1_1_a_p_i_1_1_builders_1_1_capsules_1_1_all_capsules_builder.html", null ],
      [ "Oddity.API.Builders.Capsules.CapsuleBuilder", "class_oddity_1_1_a_p_i_1_1_builders_1_1_capsules_1_1_capsule_builder.html", null ],
      [ "Oddity.API.Builders.Company.HistoryBuilder", "class_oddity_1_1_a_p_i_1_1_builders_1_1_company_1_1_history_builder.html", null ],
      [ "Oddity.API.Builders.Company.InfoBuilder", "class_oddity_1_1_a_p_i_1_1_builders_1_1_company_1_1_info_builder.html", null ],
      [ "Oddity.API.Builders.DetailedCapsules.AllDetailedCapsulesBuilder", "class_oddity_1_1_a_p_i_1_1_builders_1_1_detailed_capsules_1_1_all_detailed_capsules_builder.html", null ],
      [ "Oddity.API.Builders.DetailedCapsules.DetailedCapsuleBuilder", "class_oddity_1_1_a_p_i_1_1_builders_1_1_detailed_capsules_1_1_detailed_capsule_builder.html", null ],
      [ "Oddity.API.Builders.DetailedCores.AllDetailedCoresBuilder", "class_oddity_1_1_a_p_i_1_1_builders_1_1_detailed_cores_1_1_all_detailed_cores_builder.html", null ],
      [ "Oddity.API.Builders.DetailedCores.DetailedCoreBuilder", "class_oddity_1_1_a_p_i_1_1_builders_1_1_detailed_cores_1_1_detailed_core_builder.html", null ],
      [ "Oddity.API.Builders.Launches.LatestLaunchesBuilder", "class_oddity_1_1_a_p_i_1_1_builders_1_1_launches_1_1_latest_launches_builder.html", null ],
      [ "Oddity.API.Builders.Launches.LaunchBuilderBase< TBuilder, TReturn >", "class_oddity_1_1_a_p_i_1_1_builders_1_1_launches_1_1_launch_builder_base_3_01_t_builder_00_01_t_return_01_4.html", [
        [ "Oddity.API.Builders.Launches.AllLaunchesBuilder", "class_oddity_1_1_a_p_i_1_1_builders_1_1_launches_1_1_all_launches_builder.html", null ],
        [ "Oddity.API.Builders.Launches.PastLaunchesBuilder", "class_oddity_1_1_a_p_i_1_1_builders_1_1_launches_1_1_past_launches_builder.html", null ],
        [ "Oddity.API.Builders.Launches.UpcomingLaunchesBuilder", "class_oddity_1_1_a_p_i_1_1_builders_1_1_launches_1_1_upcoming_launches_builder.html", null ]
      ] ],
      [ "Oddity.API.Builders.Launches.NextLaunchesBuilder", "class_oddity_1_1_a_p_i_1_1_builders_1_1_launches_1_1_next_launches_builder.html", null ],
      [ "Oddity.API.Builders.Launchpads.AllLaunchpadsBuilder", "class_oddity_1_1_a_p_i_1_1_builders_1_1_launchpads_1_1_all_launchpads_builder.html", null ],
      [ "Oddity.API.Builders.Launchpads.LaunchpadBuilder", "class_oddity_1_1_a_p_i_1_1_builders_1_1_launchpads_1_1_launchpad_builder.html", null ],
      [ "Oddity.API.Builders.Roadster.RoadsterBuilder", "class_oddity_1_1_a_p_i_1_1_builders_1_1_roadster_1_1_roadster_builder.html", null ],
      [ "Oddity.API.Builders.Rockets.AllRocketsBuilder", "class_oddity_1_1_a_p_i_1_1_builders_1_1_rockets_1_1_all_rockets_builder.html", null ],
      [ "Oddity.API.Builders.Rockets.RocketBuilder", "class_oddity_1_1_a_p_i_1_1_builders_1_1_rockets_1_1_rocket_builder.html", null ]
    ] ],
    [ "Oddity.API.Builders.BuilderDelegatesContainer", "class_oddity_1_1_a_p_i_1_1_builders_1_1_builder_delegates_container.html", null ],
    [ "Oddity.API.Models.Capsule.CapsuleInfo", "class_oddity_1_1_a_p_i_1_1_models_1_1_capsule_1_1_capsule_info.html", null ],
    [ "Oddity.API.Models.DetailedCapsule.CapsuleMissionInfo", "class_oddity_1_1_a_p_i_1_1_models_1_1_detailed_capsule_1_1_capsule_mission_info.html", null ],
    [ "Oddity.API.Capsules", "class_oddity_1_1_a_p_i_1_1_capsules.html", null ],
    [ "Oddity.API.Models.Capsule.Payload.CargoInfo", "class_oddity_1_1_a_p_i_1_1_models_1_1_capsule_1_1_payload_1_1_cargo_info.html", null ],
    [ "Oddity.API.Company", "class_oddity_1_1_a_p_i_1_1_company.html", null ],
    [ "Oddity.API.Models.Company.CompanyInfo", "class_oddity_1_1_a_p_i_1_1_models_1_1_company_1_1_company_info.html", null ],
    [ "Oddity.API.Models.Launch.Rocket.FirstStage.CoreInfo", "class_oddity_1_1_a_p_i_1_1_models_1_1_launch_1_1_rocket_1_1_first_stage_1_1_core_info.html", null ],
    [ "Oddity.API.Models.DetailedCore.CoreMissionInfo", "class_oddity_1_1_a_p_i_1_1_models_1_1_detailed_core_1_1_core_mission_info.html", null ],
    [ "Oddity.API.Models.DetailedCapsule.DetailedCapsuleInfo", "class_oddity_1_1_a_p_i_1_1_models_1_1_detailed_capsule_1_1_detailed_capsule_info.html", null ],
    [ "Oddity.API.DetailedCapsules", "class_oddity_1_1_a_p_i_1_1_detailed_capsules.html", null ],
    [ "Oddity.API.Models.DetailedCore.DetailedCoreInfo", "class_oddity_1_1_a_p_i_1_1_models_1_1_detailed_core_1_1_detailed_core_info.html", null ],
    [ "Oddity.API.DetailedCores", "class_oddity_1_1_a_p_i_1_1_detailed_cores.html", null ],
    [ "Oddity.API.Models.Rocket.Engines.EnginesInfo", "class_oddity_1_1_a_p_i_1_1_models_1_1_rocket_1_1_engines_1_1_engines_info.html", null ],
    [ "EventArgs", null, [
      [ "Oddity.API.Builders.RequestSendEventArgs", "class_oddity_1_1_a_p_i_1_1_builders_1_1_request_send_event_args.html", null ],
      [ "Oddity.API.Builders.ResponseReceiveEventArgs", "class_oddity_1_1_a_p_i_1_1_builders_1_1_response_receive_event_args.html", null ]
    ] ],
    [ "Oddity.API.Models.Company.EventLinks", "class_oddity_1_1_a_p_i_1_1_models_1_1_company_1_1_event_links.html", null ],
    [ "Exception", null, [
      [ "Oddity.API.Exceptions.APIUnavailableException", "class_oddity_1_1_a_p_i_1_1_exceptions_1_1_a_p_i_unavailable_exception.html", null ]
    ] ],
    [ "Oddity.API.Models.Rocket.Stages.Payloads.FairingInfo", "class_oddity_1_1_a_p_i_1_1_models_1_1_rocket_1_1_stages_1_1_payloads_1_1_fairing_info.html", null ],
    [ "Oddity.API.Models.Rocket.Stages.FirstStageInfo", "class_oddity_1_1_a_p_i_1_1_models_1_1_rocket_1_1_stages_1_1_first_stage_info.html", null ],
    [ "Oddity.API.Models.Launch.Rocket.FirstStage.FirstStageInfo", "class_oddity_1_1_a_p_i_1_1_models_1_1_launch_1_1_rocket_1_1_first_stage_1_1_first_stage_info.html", null ],
    [ "Oddity.API.Models.Company.Headquarters", "class_oddity_1_1_a_p_i_1_1_models_1_1_company_1_1_headquarters.html", null ],
    [ "Oddity.API.Models.Capsule.Heatshield.HeatshieldInfo", "class_oddity_1_1_a_p_i_1_1_models_1_1_capsule_1_1_heatshield_1_1_heatshield_info.html", null ],
    [ "Oddity.API.Models.Company.HistoryEvent", "class_oddity_1_1_a_p_i_1_1_models_1_1_company_1_1_history_event.html", null ],
    [ "IDisposable", null, [
      [ "Oddity.OddityCore", "class_oddity_1_1_oddity_core.html", null ]
    ] ],
    [ "Oddity.API.Models.Rocket.LandingLegs.LandingLegsInfo", "class_oddity_1_1_a_p_i_1_1_models_1_1_rocket_1_1_landing_legs_1_1_landing_legs_info.html", null ],
    [ "Oddity.API.Launches", "class_oddity_1_1_a_p_i_1_1_launches.html", null ],
    [ "Oddity.API.Models.Launch.LaunchInfo", "class_oddity_1_1_a_p_i_1_1_models_1_1_launch_1_1_launch_info.html", null ],
    [ "Oddity.API.Models.Launchpad.LaunchpadInfo", "class_oddity_1_1_a_p_i_1_1_models_1_1_launchpad_1_1_launchpad_info.html", null ],
    [ "Oddity.API.Models.Launchpad.LaunchpadLocation", "class_oddity_1_1_a_p_i_1_1_models_1_1_launchpad_1_1_launchpad_location.html", null ],
    [ "Oddity.API.Launchpads", "class_oddity_1_1_a_p_i_1_1_launchpads.html", null ],
    [ "Oddity.API.Models.Launch.LaunchSiteInfo", "class_oddity_1_1_a_p_i_1_1_models_1_1_launch_1_1_launch_site_info.html", null ],
    [ "Oddity.API.Models.Launch.LinksInfo", "class_oddity_1_1_a_p_i_1_1_models_1_1_launch_1_1_links_info.html", null ],
    [ "Oddity.API.Models.Common.MassInfo", "class_oddity_1_1_a_p_i_1_1_models_1_1_common_1_1_mass_info.html", null ],
    [ "Oddity.API.Models.Launch.Rocket.SecondStage.Orbit.OrbitParameters", "class_oddity_1_1_a_p_i_1_1_models_1_1_launch_1_1_rocket_1_1_second_stage_1_1_orbit_1_1_orbit_parameters.html", null ],
    [ "Oddity.API.Models.Rocket.Stages.Payloads.PayloadInfo", "class_oddity_1_1_a_p_i_1_1_models_1_1_rocket_1_1_stages_1_1_payloads_1_1_payload_info.html", null ],
    [ "Oddity.API.Models.Launch.Rocket.SecondStage.PayloadInfo", "class_oddity_1_1_a_p_i_1_1_models_1_1_launch_1_1_rocket_1_1_second_stage_1_1_payload_info.html", null ],
    [ "Oddity.API.Models.Rocket.PayloadWeights.PayloadWeightInfo", "class_oddity_1_1_a_p_i_1_1_models_1_1_rocket_1_1_payload_weights_1_1_payload_weight_info.html", null ],
    [ "Oddity.API.Models.Capsule.Payload.PressurizedCapsuleInfo", "class_oddity_1_1_a_p_i_1_1_models_1_1_capsule_1_1_payload_1_1_pressurized_capsule_info.html", null ],
    [ "Oddity.API.Models.Launch.ReuseInfo", "class_oddity_1_1_a_p_i_1_1_models_1_1_launch_1_1_reuse_info.html", null ],
    [ "Oddity.API.Roadster", "class_oddity_1_1_a_p_i_1_1_roadster.html", null ],
    [ "Oddity.API.Models.Roadster.RoadsterInfo", "class_oddity_1_1_a_p_i_1_1_models_1_1_roadster_1_1_roadster_info.html", null ],
    [ "Oddity.API.Models.Launch.Rocket.RocketInfo", "class_oddity_1_1_a_p_i_1_1_models_1_1_launch_1_1_rocket_1_1_rocket_info.html", null ],
    [ "Oddity.API.Models.Rocket.RocketInfo", "class_oddity_1_1_a_p_i_1_1_models_1_1_rocket_1_1_rocket_info.html", null ],
    [ "Oddity.API.Rockets", "class_oddity_1_1_a_p_i_1_1_rockets.html", null ],
    [ "Oddity.API.Models.Launch.Rocket.SecondStage.SecondStageInfo", "class_oddity_1_1_a_p_i_1_1_models_1_1_launch_1_1_rocket_1_1_second_stage_1_1_second_stage_info.html", null ],
    [ "Oddity.API.Models.Rocket.Stages.SecondStageInfo", "class_oddity_1_1_a_p_i_1_1_models_1_1_rocket_1_1_stages_1_1_second_stage_info.html", null ],
    [ "Oddity.API.Models.Common.SizeInfo", "class_oddity_1_1_a_p_i_1_1_models_1_1_common_1_1_size_info.html", null ],
    [ "Oddity.API.Models.Launch.TelemetryInfo", "class_oddity_1_1_a_p_i_1_1_models_1_1_launch_1_1_telemetry_info.html", null ],
    [ "Oddity.API.Models.Capsule.Thrusters.ThrustersInfo", "class_oddity_1_1_a_p_i_1_1_models_1_1_capsule_1_1_thrusters_1_1_thrusters_info.html", null ],
    [ "Oddity.API.Models.Common.ThrustInfo", "class_oddity_1_1_a_p_i_1_1_models_1_1_common_1_1_thrust_info.html", null ],
    [ "Oddity.API.Models.Capsule.Payload.TrunkInfo", "class_oddity_1_1_a_p_i_1_1_models_1_1_capsule_1_1_payload_1_1_trunk_info.html", null ],
    [ "Oddity.API.Models.Common.VolumeInfo", "class_oddity_1_1_a_p_i_1_1_models_1_1_common_1_1_volume_info.html", null ]
];