var namespace_oddity_1_1_a_p_i_1_1_builders_1_1_detailed_capsules =
[
    [ "AllDetailedCapsulesBuilder", "class_oddity_1_1_a_p_i_1_1_builders_1_1_detailed_capsules_1_1_all_detailed_capsules_builder.html", "class_oddity_1_1_a_p_i_1_1_builders_1_1_detailed_capsules_1_1_all_detailed_capsules_builder" ],
    [ "DetailedCapsuleBuilder", "class_oddity_1_1_a_p_i_1_1_builders_1_1_detailed_capsules_1_1_detailed_capsule_builder.html", "class_oddity_1_1_a_p_i_1_1_builders_1_1_detailed_capsules_1_1_detailed_capsule_builder" ]
];